#!/bin/bash

maindir="$(pwd)"
ver=$(head -1 version)
stamp=$(date +%Y%m%d%H)
target=$1
isJakarta=$2
echo "is jakarta?$pver"
if [ "$isJakarta" = "true" ] ; then
	pver=$ver-jakarta
fi
echo $pver

if [ "$target" = "FL" ] ; then
	pver=$pver-FL-$stamp
fi

echo $pver

bash ./upVer $ver-SNAPSHOT $pver

cd zats
mvn clean install -am -Dmaven.test.skip
mvn source:jar javadoc:jar repository:bundle-create --batch-mode -Dmaven.test.skip -P disable-java8-doclint

cd $maindir
bash ./prepare-upload.sh $pver