#!/bin/bash
# release
#
#{{IS_NOTE
#	Purpose:
#		
#	Description:
#		
#	History:
#		Tue Mar 3 11:11:09     2011, Created by Jimmy
#}}IS_NOTE
#
#Copyright (C) 2011 Potix Corporation. All Rights Reserved.
#
#{{IS_RIGHT
#}}IS_RIGHT
#
maindir="$(pwd)"
echo "Working directory $maindir"
stamp=$(date +%Y%m%d)
oldVersion=$1
newVersion=$2
isFL=$3

if [ "$Zats" = "" ] ; then
	if [ ! -d "./zats" ] ; then
		echo "Zats path is not found!!"
	fi
	if [ ! -d "./zats-common" ] ; then
		echo "zats-common path is not found!!"
	fi
	if [ ! -d "./zats-example" ] ; then
		echo "zats-example path is not found!!"
	fi
	if [ ! -d "./zats-mimic" ] ; then
		echo "zats-mimic path is not found!!"
	fi
	if [ ! -d "./zats-mimic-ext" ] ; then
		echo "zats-mimic-ext path is not found!!"
	fi
	Zats=$maindir
fi

if [ "$oldVersion" == "" ] || [ "$newVersion" == "" ] ; then
	echo "Usage: upVer [ oldVersion ] [ newVersion ] [options]"
	echo "Available options: FL."
	exit 1
fi

function upVer {
	if [ "$isFL" == "FL" ] ; then
		sed -i "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion-SNAPSHOT<\//" $1/pom.xml
		echo "$1 pom.xml"
		grep -n --color=auto $newVersion"-SNAPSHOT" $1/pom.xml
	else
		sed -i "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion<\//" $1/pom.xml
		echo "$1 pom.xml"
		grep -n --color=auto $newVersion $1/pom.xml
	fi
	
}

upVer zats
upVer zats-common
upVer zats-example
upVer zats-mimic
upVer zats-mimic-ext
upVer zats-example