#!/bin/bash
# release
#
#{{IS_NOTE
#	Purpose:
#		
#	Description:
#		
#	History:
#		Tue Mar 3 11:11:09     2011, Created by Jimmy
#}}IS_NOTE
#
#Copyright (C) 2011 Potix Corporation. All Rights Reserved.
#
#{{IS_RIGHT
#}}IS_RIGHT
#
maindir="$(pwd)"
echo "Working directory $maindir"
stamp=$(date +%Y%m%d)
oldVersion=$1
newVersion=$2
isFL=$3

if [ "$Zats" = "" ] ; then
	if [ ! -d "./zats" ] ; then
		echo "Zats path is not found!!"
	fi
	if [ ! -d "./zats-common" ] ; then
		echo "zats-common path is not found!!"
	fi
	if [ ! -d "./zats-example" ] ; then
		echo "zats-example path is not found!!"
	fi
	if [ ! -d "./zats-mimic" ] ; then
		echo "zats-mimic path is not found!!"
	fi
	if [ ! -d "./zats-mimic-ext6" ] ; then
		echo "zats-mimic-ext6 path is not found!!"
	fi
	if [ ! -d "./zats-mimic-ext7" ] ; then
		echo "zats-mimic-ext7 path is not found!!"
	fi
	Zats=$maindir
fi

if [ "$oldVersion" == "" ] || [ "$newVersion" == "" ] ; then
	echo "Usage: upVer [ oldVersion ] [ newVersion ] [options]"
	echo "Available options: FL."
	exit 1
fi

function upVer {
	if [ "$isFL" == "FL" ] ; then
		sed -i "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion-SNAPSHOT<\//" $1/pom.xml
		echo "$1 pom.xml"
		grep -n --color=auto $newVersion"-SNAPSHOT" $1/pom.xml
	else
		sed -i "/version>/,/<\//s/>$oldVersion.*<\//>$newVersion<\//" $1/pom.xml
		echo "$1 pom.xml"
		grep -n --color=auto $newVersion $1/pom.xml
	fi
	
	# sed -i "s/$oldVersion.*/$newVersion/g" $1/version
	# echo "$1 version"
	# grep -n --color=auto $newVersion $1/version
	
	# echo "$1 MANIFEST.MF"
	# find $1/src -name MANIFEST.MF -exec sed -i "s/$oldVersion.*/$newVersion/g
	# " {} \; -exec grep -n --color=auto $newVersion {} \;
	
	# echo "$1 config.xml"
	# find $1/src -name config.xml -exec sed -i "
	# /<version/,/\/version>/s/>$oldVersion.*<\//>$newVersion<\//g
	# " {} \; -exec grep -n --color=auto $newVersion {} \;
	
	# echo "$1 lang.xml"
	# find $1/src -name lang.xml -exec sed -i "
	# /<version/,/\/version>/s/>$oldVersion.*<\//>$newVersion<\//g
	# " {} \; -exec grep -n --color=auto $newVersion {} \;
	
	# echo "$1 lang-addon.xml"
	# find $1/src -name lang-addon.xml -exec sed -i "
	# /<version/,/\/version>/s/>$oldVersion.*<\//>$newVersion<\//g
	# " {} \; -exec grep -n --color=auto $newVersion {} \;
	
	# echo "$1 lang-addon.xml javascript"
	# find $1/src -name lang-addon.xml -exec sed -i "
	# s/version=\"$oldVersion.*\"/version=\"$newVersion\"/g
	# " {} \; -exec grep -n --color=auto $newVersion {} \;
	
	# echo "$1 Version.java"
	# find $1/src -name Version.java -exec sed -i "
	# s/UID = \"$oldVersion.*\";/UID = \"$newVersion\";/g
	# " {} \; -exec grep -n --color=auto $newVersion {} \;
}

upVer zats
upVer zats-common
upVer zats-example
upVer zats-mimic
upVer zats-mimic-ext6
upVer zats-mimic-ext7